config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  root to: "interviews#index"

  resources :profiles do
  end

  resources :interviews do
    collection do
      get :complete
      get :mypage
      get :adminpage
      get :search
    end
  end
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end 
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interview.rb
class Interview < ApplicationRecord

  belongs_to :user
  belongs_to :profile

  validates :generic,
  presence: true


end

app/models/profile.rb
class Profile < ApplicationRecord

  validates :family_name,
  presence: true,                     # 必須
  format: { with: /\A[ぁ-んァ-ン一-龥]/ } 

  validates :first_name,
  presence: true,
  format: { with: /\A[ぁ-んァ-ン一-龥]/ } 

  validates :family_name_kana,
  presence: true,
  format: { with: /\A[ァ-ヶー－]+\z/ } 

  validates :first_name_kana,
  presence: true,
  format: { with: /\A[ァ-ヶー－]+\z/ }
  
  validates :birth,
  presence: true

  validates :prefecuture,
  presence: true,
  format: { with: /\A[ぁ-んァ-ン一-龥]/ } 

  validates :city,
  presence: true,
  format: { with: /\A[ぁ-んァ-ン一-龥]/ }   
  
  validates :address,
  presence: true

  validates :telephone_number,
  presence: true,
  format: { with: /\A[0-9]+\z/ }

  belongs_to :user
  has_many :interviews

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  validates :nickname,
  presence: true,                     # 必須
  uniqueness: true,                   # 一意性
  length: { maximum: 20 }            # あんまり長いのも

  validates :email,
  presence: true,
  uniqueness: true,
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }  # メールアドレスの正規表現

  validates :password,
  presence: true,                     # 必須
  length: { minimum: 7 },            # 7文字以上
  format: { with: /\A[a-z0-9]+\z/i }  # 半角英数字のみ

  has_one :profile
  has_many :interviews

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if user_signed_in? && current_user.id == 1
      adminpage_interviews_path
    else
      @user = current_user
      @profile = Profile.find_by(user_id: current_user.id)
      if @profile.nil?
        new_profile_path(@user)
      else
        new_interview_path(@user)
      end
    end
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email, :password])
  end
  
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :medical_history_string, only: [:create, :update]
  before_action :life_details_string, only: [:create, :update]
  before_action :dosage_form_string, only: [:create, :update]

  def index
  end

  def new
    @interview = Interview.new
  end

  def create
    @interview = Interview.new(interview_params)
    unless @interview.valid?
      render :new and return
    end
    @interview.save
    redirect_to  complete_interviews_path and return
  end

  def show
    @interviews = Interview.find(params[:id])
    @profile = @interviews.profile
  end

  def medical_history_string
    if params[:interview][:medical_history].present?
      params[:interview][:medical_history] = params[:interview][:medical_history].join("、")
    end
  end

  def life_details_string
    if params[:interview][:life_details].present?
      params[:interview][:life_details] = params[:interview][:life_details].join("、")
    end
  end

  def dosage_form_string
    if params[:interview][:dosage_form].present?
      params[:interview][:dosage_form] = params[:interview][:dosage_form].join("、")
    end
  end

  def complete
  end

  def mypage
    @user = current_user
    @profile = Profile.find_by(user_id: current_user.id)
    @interviews = Interview.where(user_id:current_user.id).order("created_at DESC")
  end

  def adminpage
    if user_signed_in? && current_user.id == 1
      @interviews = Interview.joins(:profile).order("created_at DESC").page(params[:page]).per(13)
    else
      redirect_to root_path
    end
  end

  def search
    if user_signed_in? && current_user.id == 1
      if
        @interviews = Interview.joins(:profile).where('family_name_kana LIKE ? OR first_name_kana LIKE ?', "%#{params[:search]}%","%#{params[:search]}%").order("created_at DESC").page(params[:page]).per(13)
      else
        @interviews = Interview.all.joins(:profile).order("created_at DESC").page(params[:page]).per(13)
      end
    else
      redirect_to root_path
    end
  end

  private

  def interview_params
    params.require(:interview).permit(
      :diagnosis, 
      :se_medicine,
      :se_symptom,
      :allergy,
      :supplement,
      :drinking,
      :smoking,
      :pregnancy,
      :breastfeeding,
      :child_weight,
      :generic,
      :dosage_form,
      :life_details,
      :medical_history,
      :medical_history_etc).merge(user_id: current_user.id).merge(profile_id: current_user.id)
  end



end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end

  def create
    @user = current_user
    @profile = Profile.new(profile_params)
    unless @profile.valid?
      render :new and return
    end
    @profile.save
    redirect_to  new_interview_path(@user) and return
  end

  def edit
    @profile = Profile.find_by(user_id: current_user.id)
  end

  def update
    @profile = Profile.find_by(user_id: current_user.id)
    unless @profile.valid?
      render :edit and return
    end
    @profile.update(profile_params)
    redirect_to  mypage_interviews_path and return
  end

  private

  def profile_params
    params.require(:profile).permit(
      :family_name, 
      :first_name,
      :family_name_kana,
      :first_name_kana,
      :birth,
      :sex,
      :zip_code,
      :prefecuture,
      :city,
      :address,
      :building_name,
      :telephone_number).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/interviews/adminpage.html.haml
.admin
  .admin__header
    = render "/layouts/header"
  .admin__search
    = form_tag(search_interviews_path, method: 'get') do
      -# = label_tag(:search)
      = text_field_tag(:search, '', class: 'search_input', placeholder: '患者氏名検索（例：ヤッキョク ハナコ）')
      = submit_tag('検索',class: "search_btn")
  .admin__in
    %table.mypage__in__profiles
      - @interviews.each do |i|
        %tr
          %td.left
            = i.created_at.strftime('%Y/%m/%d')
          %td.right
            = link_to interview_path(i.id) do
              = i.profile.family_name
              = i.profile.first_name
              (
              = i.profile.family_name_kana
              = i.profile.first_name_kana
              )
          = paginate @interviews
  .admin__logout
    = link_to '管理者画面を終了する', destroy_user_session_path, method: :delete

app/views/interviews/complete.html.haml
.complete
  .complete__in
    = image_tag("mediask_logo_big.png", class: "logobig")
    %br/
    問診票の回答が完了しました。
    %br/
    お席にかけてお待ちください。
    %br/
    %br/
    = link_to "登録情報を確認する" ,mypage_interviews_path(id: current_user.id)
    = link_to 'トップページに戻る', destroy_user_session_path, method: :delete

app/views/interviews/index.html.haml
.top
  .top__header
    -# = link_to icon('fas ', 'clinic-medical'), root_path
  .top__main
    .top__main__in
      .top__main__in__upper
        = image_tag("mediask_logo_big.png", class: "logobig")
      .top__main__in__downer
        %ul
          %li
          問診票を記入する
          %li
          = link_to "新規登録（初めての方）" ,new_user_registration_path
          %li
          = link_to "ログイン（２度目以降の方）" ,new_user_session_path

app/views/interviews/mypage.haml
.header
  = render "/layouts/header"
.mypage
  .mypage__in
    %table.mypage__in__users
      %tr
        %td.left
          ニックネーム
        %td.right
          = @user.nickname
      %tr
        %td.left
          メールアドレス
        %td.right
          = @user.email
      %tr
        %td.left
          パスワード
        %td.right
          表示されません
    %br/
    %table.mypage__in__profiles
      %tr
        %td.left
          お名前（全角）
        %td.right
          = @profile.family_name
          = @profile.first_name
      %tr
        %td.left
          お名前（カナ）
        %td.right
          = @profile.family_name_kana
          = @profile.first_name_kana
      %tr
        %td.left
          生年月日
        %td.right
          = @profile.birth
      %tr
        %td.left
          性別
        %td.right
          = @profile.sex
      %tr
        %td.left
          住所
        %td.right
          = @profile.zip_code
          = @profile.prefecuture
          = @profile.city
          = @profile.address
          = @profile.building_name
      %tr
        %td.left
          電話番号
        %td.right
          = @profile.telephone_number
    .mypage__in__edit
      = link_to "登録情報を編集する" ,edit_profile_path(@user)
    .mypage__in__interviews
      %h1
        過去の問診票
      %br/
      - @interviews.each do |i|
        %h2
          ●
          = link_to i.created_at.strftime('%Y/%m/%d')+"  入力分",interview_path(i.id)
    .mypage__in__back
      = link_to 'トップページに戻る', destroy_user_session_path, method: :delete

app/views/interviews/new.html.haml
.header
  = render "/layouts/header"
.header2
  ユーザー情報登録 > 
  患者情報登録 > 
  %label
    問診票回答
.interviewsform
  .interviewsform__in
    = form_for [@interview] do |f|
      = render 'layouts/validationerror', model: f.object
      .interviewsform__in__diagnosis
        %h1
          1.今回病院にかかられた症状、診断名が分かればご入力ください。
        = f.text_field :diagnosis, class: 'input', placeholder: '例）鼻水が出る、熱っぽい、過敏性腸症候群'
      .interviewsform__in__se_medicine
        %h1
          2.薬で副作用が起きたことがありますか？
          %br/
        %h2
          薬の名前
        = f.text_field :se_medicine, class: 'input', placeholder: '例）クラビット'
      .interviewsform__in__se_symptom
        %h2
          症状
        = f.text_field :se_symptom, class: 'input', placeholder: '例）お腹を下したことがあります'
      .interviewsform__in__allergy
        %h1
          3.アレルギーはありますか？
        = f.text_field :allergy, class: 'input', placeholder: '例）セフェム系抗生物質、食物、動物、花粉症など'
      .interviewsform__in__medical_history
        %h1
          4.現在、他の医療機関で治療中の病気はありますか？
        %label{class:"check"}
          = f.check_box :medical_history ,{multiple: true}, "高血圧",nil
          高血圧
        %br/
        %label{class:"check"}
          = f.check_box :medical_history ,{multiple: true}, "心臓疾患",nil
          心臓疾患
        %br/
        %label{class:"check"}
          = f.check_box :medical_history ,{multiple: true}, "脳梗塞",nil
          脳梗塞
        %br/
        %label{class:"check"}
          = f.check_box :medical_history ,{multiple: true}, "脂質異常症",nil
          脂質異常症
        %br/
        %label{class:"check"}
          = f.check_box :medical_history ,{multiple: true}, "糖尿病",nil
          糖尿病
        %br/
        %label{class:"check"}
          = f.check_box :medical_history ,{multiple: true}, "肝臓病",nil
          肝臓病
        %br/
        %label{class:"check"}
          = f.check_box :medical_history ,{multiple: true}, "腎臓病",nil
          腎臓病
        %br/
        %label{class:"check"}
          = f.check_box :medical_history ,{multiple: true}, "緑内障",nil
          緑内障
        %br/
        %label{class:"check"}
          = f.check_box :medical_history ,{multiple: true}, "前立腺疾患",nil
          前立腺疾患
        %br/
        %label{class:"check"}
          = f.check_box :medical_history ,{multiple: true}, "甲状腺疾患",nil
          甲状腺疾患
        %br/
        %label{class:"check"}
          = f.check_box :medical_history ,{multiple: true}, "胃・十二指腸潰瘍",nil
          胃・十二指腸潰瘍
        %br/
        %label{class:"check"}
          = f.check_box :medical_history ,{multiple: true}, "リウマチ",nil
          リウマチ
        %br/
        %label{class:"check"}
          = f.check_box :medical_history ,{multiple: true}, "骨粗しょう症",nil
          骨粗しょう症
        %br/
        %h2
          %br/
          その他
        = f.text_field :medical_history_etc, class: 'input', placeholder: 'その他あれば入力してください'
      .profilesform__in__supplement
        %h1
          5.お薬手帳に記載してあるもの以外に、現在服用している薬やサプリメントはありますか？
        = f.text_field :supplement, class: 'input', placeholder: '例）ビタミン（A,Cなど）、にんにく卵黄'
      .profilesform__in__life_details
        %h1
          6.自動車運転など、生活に当てはまるものがあれば教えてください。
        %label
          = f.check_box :life_details ,{multiple: true}, "自動車の運転をする",nil
          自動車の運転をする
        %br/
        %label
          = f.check_box :life_details ,{multiple: true}, "視力をよく使う",nil
          視力をよく使う
        %br/
        %label
          = f.check_box :life_details ,{multiple: true}, "高所など危険な場所での仕事をする",nil
          高所など危険な場所での仕事をする
        %br/
        %label
          = f.check_box :life_details ,{multiple: true}, "夜勤などで不規則",nil
          夜勤などで不規則
        %br/
        %br/
      .interviewsform__in__drinking
        %h1
          7.お酒は飲みますか？
        %label{class:"radiocheck"}
          = f.radio_button :drinking, "よく飲む"
          よく飲む
        %label{class:"radiocheck"}
          = f.radio_button :drinking, "たまに飲む"
          たまに飲む
        %label{class:"radiocheck"}
          = f.radio_button :drinking, "全く飲まない"
          全く飲まない
        %br/
        %br/
      .interviewsform__in__smoking
        %h1
          8.タバコは吸いますか？
        %label{class:"radiocheck"}
          = f.radio_button :smoking, "よく吸う"
          よく吸う
        %label{class:"radiocheck"}
          = f.radio_button :smoking, "たまに吸う"
          たまに吸う
        %label{class:"radiocheck"}
          = f.radio_button :smoking, "全く吸わない"
          全く吸わない
        %br/
        %br/
      .interviewsform__in__dosage_form
        %h1
          9.飲めない形の薬があれば教えてください
        %label{class:"radiocheck"}
          = f.check_box :dosage_form ,{multiple: true}, "粉薬",nil
          粉薬
        %label{class:"radiocheck"}
          = f.check_box :dosage_form ,{multiple: true}, "錠剤",nil
          錠剤
        %label{class:"radiocheck"}
          = f.check_box :dosage_form ,{multiple: true}, "カプセル",nil
          カプセル
        %label{class:"radiocheck"}
          = f.check_box :dosage_form ,{multiple: true}, "水薬",nil
          水薬
        %br/
        %br/
      .interviewsform__in__pregnancy
        %h1
          10.女性の方に伺います。妊娠中、または妊娠している可能性がありますか？
        %label{class:"radiocheck"}
          = f.radio_button :pregnancy, "妊娠している"
          はい
        %label{class:"radiocheck"}
          = f.radio_button :pregnancy, "妊娠していない"
          いいえ
        %br/
        %br/
      .interviewsform__in__breastfeeding
        %h1
          11.女性の方に伺います。現在、授乳中ですか？
        %label{class:"radiocheck"}
          = f.radio_button :breastfeeding, "授乳中である"
          はい
        %label{class:"radiocheck"}
          = f.radio_button :breastfeeding, "授乳中でない"
          いいえ
        %br/
        %br/
      .interviewsform__in__child_weight
        %h1
          12.小児（子ども）の方は、現在の体重を教えてください。
        = f.text_field :child_weight, class: 'input', placeholder: '例）10kg'
      .interviewsform__in__generic
        %h1
          13.ジェネリック医薬品（後発品）に変更できる処方箋であった場合、変更を希望されますか？
          %span 必須
        %label{class:"radiocheck"}
          = f.radio_button :generic, "ジェネリック医薬品希望"
          はい
        %label{class:"radiocheck"}
          = f.radio_button :generic, "先発品希望"
          いいえ
      .interviewsform__in__send
        = f.submit '回答を送信する', class: 'button'

app/views/interviews/search.html.haml
.admin
  .admin__header
    = render "/layouts/header"
  .admin__in
    %table.mypage__in__profiles
      - @interviews.each do |i|
        %tr
          %td.left
            = i.created_at.strftime('%Y/%m/%d')
          %td.right
            = link_to interview_path(i.id) do
              = i.profile.family_name
              = i.profile.first_name
              (
              = i.profile.family_name_kana
              = i.profile.first_name_kana
              )
          = paginate @interviews
  .admin__logout
    = link_to '患者一覧画面に戻る', adminpage_interviews_path

app/views/interviews/show.html.haml
.header
  = render "/layouts/header"
.interviews_show
  .interviews_show__in
    = @profile.family_name
    = @profile.first_name
    (
    = @profile.family_name_kana
    = @profile.first_name_kana
    )
    %br/
    = @interviews.created_at.strftime('%Y/%m/%d')+"  入力分"
    %br/
    %br/
    %table.interviews_show
      %tr
        %td.left
          診断名
        %td.right
          = @interviews.diagnosis
      %tr
        %td.left
          副作用歴（薬の名前）
        %td.right
          = @interviews.se_medicine
      %tr
        %td.left
          副作用歴（症状）
        %td.right
          = @interviews.se_symptom
      %tr
        %td.left
          アレルギー
        %td.right
          = @interviews.allergy
      %tr
        %td.left
          現病歴・既往歴
        %td.right
          = @interviews.medical_history
          = @interviews.medical_history_etc
      %tr
        %td.left
          現在服用中のサプリメント
        %td.right
          = @interviews.supplement
      %tr
        %td.left
          生活特記
        %td.right
          = @interviews.life_details
      %tr
        %td.left
          飲酒
        %td.right
          = @interviews.drinking
      %tr
        %td.left
          喫煙
        %td.right
          = @interviews.smoking
      %tr
        %td.left
          服用不可な剤形
        %td.right
          = @interviews.dosage_form
      %tr
        %td.left
          妊娠の有無
        %td.right
          = @interviews.pregnancy
      %tr
        %td.left
          授乳中の有無
        %td.right
          = @interviews.breastfeeding
      %tr
        %td.left
          小児の体重
        %td.right
          = @interviews.child_weight
      %tr
        %td.left
          ジェネリック可否
        %td.right
          = @interviews.generic
    .interviews_show__in__back
      - if user_signed_in? && current_user.id == 1
        = link_to '問診票一覧に戻る', adminpage_interviews_path
      - else
        = link_to '一覧に戻る', mypage_interviews_path

app/views/layouts/_header.html.haml
.header
  = image_tag("mediask_logo_small.png", class: "logosmall")

app/views/layouts/_validationerror.html.haml
-if model.errors.any? 
  .alert
    %ul
      -model.errors.full_messages.each do |message| 
        %li= message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MEDIASK
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/profiles/edit.html.haml
.header
  = render "/layouts/header"
.header2
.profilesform
  .profilesform__in
    = form_for [@profile] do |f|
      = render 'layouts/validationerror', model: f.object
      .profilesform__in__name
        %h1
          お名前（全角）
          %span 必須
        %h2
          = f.text_field :family_name, class: 'input', placeholder: '例）薬局'
          = f.text_field :first_name, class: 'input', placeholder: '例）花子'
      .profilesform__in__kana
        %h1
          お名前（カナ）
          %span 必須
        %h2
          = f.text_field :family_name_kana, class: 'input', placeholder: '例）ヤッキョク'
          = f.text_field :first_name_kana, class: 'input', placeholder: '例）ハナコ'
      .profilesform__in__birth
        %h1
          生年月日
          %span 必須
          %br/
        = f.text_field :birth, class: 'input', placeholder: '例）19911206 西暦で入力'
      .profilesform__in__sex
        %h1
          性別
        = f.radio_button :sex, "男性", class: 'inputsex'
        = f.label :sex, "男性", {value: "男性", style: "display: inline-block;"}
        = f.radio_button :sex, "女性", class: 'inputxse'
        = f.label :sex, "女性", {value: "女性", style: "display: inline-block;"}
        = f.radio_button :sex, "回答しない", class: 'inputsex'
        = f.label :sex, "回答しない", {value: "回答しない", style: "display: inline-block;"}
      .profilesform__in__zipcode
        %h1
          郵便番号
        = f.text_field :zip_code, class: 'input', placeholder: '例）123-4567'
      .profilesform__in__prefecuture
        %h1
          都道府県
          %span 必須
        = f.text_field :prefecuture, class: 'input', placeholder: '例）大阪府'
      .profilesform__in__city
        %h1
          市区町村
          %span 必須
        = f.text_field :city, class: 'input', placeholder: '例）大阪市北区中崎町'
      .profilesform__in__address
        %h1
          番地
          %span 必須
        = f.text_field :address, class: 'input', placeholder: '例）１丁目１−１'
      .profilesform__in__buildingname
        %h1
          建物名
        = f.text_field :building_name, class: 'input', placeholder: '例）メディカルマンション101号室'
      .profilesform__in__telephone
        %h1
          電話番号
          %span 必須
        = f.text_field :telephone_number, class: 'input', placeholder: '例）09012345678 ※ハイフン無し'
      .profilesform__in__send
        = f.submit '登録情報を変更する', class: 'button'

app/views/profiles/new.html.haml
.header
  = render "/layouts/header"
.header2
  ユーザー情報登録 > 
  %label
    患者情報登録
  > 問診票回答
.profilesform
  .profilesform__in
    = form_for [@profile] do |f|
      = render 'layouts/validationerror', model: f.object
      .profilesform__in__name
        %h1
          お名前（全角）
          %span 必須
        %h2
          = f.text_field :family_name, class: 'input', placeholder: '例）薬局'
          = f.text_field :first_name, class: 'input', placeholder: '例）花子'
      .profilesform__in__kana
        %h1
          お名前（カナ）
          %span 必須
        %h2
          = f.text_field :family_name_kana, class: 'input', placeholder: '例）ヤッキョク'
          = f.text_field :first_name_kana, class: 'input', placeholder: '例）ハナコ'
      .profilesform__in__birth
        %h1
          生年月日
          %span 必須
          %br/
        = f.text_field :birth, class: 'input', placeholder: '例）19911206 西暦で入力'
      .profilesform__in__sex
        %h1
          性別
        = f.radio_button :sex, "男性", class: 'inputsex'
        = f.label :sex, "男性", {value: "男性", style: "display: inline-block;"}
        = f.radio_button :sex, "女性", class: 'inputxse'
        = f.label :sex, "女性", {value: "女性", style: "display: inline-block;"}
        = f.radio_button :sex, "回答しない", class: 'inputsex'
        = f.label :sex, "回答しない", {value: "回答しない", style: "display: inline-block;"}
      .profilesform__in__zipcode
        %h1
          郵便番号
        = f.text_field :zip_code, class: 'input', placeholder: '例）123-4567'
      .profilesform__in__prefecuture
        %h1
          都道府県
          %span 必須
        = f.text_field :prefecuture, class: 'input', placeholder: '例）大阪府'
      .profilesform__in__city
        %h1
          市区町村
          %span 必須
        = f.text_field :city, class: 'input', placeholder: '例）大阪市北区中崎町'
      .profilesform__in__address
        %h1
          番地
          %span 必須
        = f.text_field :address, class: 'input', placeholder: '例）１丁目１−１'
      .profilesform__in__buildingname
        %h1
          建物名
        = f.text_field :building_name, class: 'input', placeholder: '例）メディカルマンション101号室'
      .profilesform__in__telephone
        %h1
          電話番号
          %span 必須
        = f.text_field :telephone_number, class: 'input', placeholder: '例）09012345678 ※ハイフン無し'
      .profilesform__in__send
        = f.submit '問診の回答へ', class: 'button'